[Paths]
# Wpisz pełną ścieżkę do ffmpeg.exe. Jeśli linia jest zakomentowana (#) lub pusta, użyta zostanie ścieżka domyślna.
ffmpeg = C:\Program Files\ffmpeg\bin\ffmpeg.exe

# Wpisz pełną ścieżkę do magick.exe (ImageMagick).
imagemagick = C:\Program Files\ImageMagick\magick.exe